version: 0.2
phases:
  pre_build:
    commands:
        - echo `aws --version`
        - echo Logging in to Amazon ECR...
        - $(aws ecr get-login --region $AWS_REGION --no-include-email)
        - REPOSITORY_URI=${REPOSITORY_URL}
        - CONTAINER_NAME=${CONTAINER_NAME}
  build:
    commands:
        - echo Build started on `date`
        - echo Building the Docker image...
        - echo `docker --version`
        - echo $REPOSITORY_URL
        - echo $IMAGE_TAG
        - echo $CODEBUILD_SOURCE_VERSION
        - docker build -t $REPOSITORY_URL:latest .
        - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
        - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$(echo $CODEBUILD_BUILD_ID | sed 's/:/-/')
  post_build:
    commands:
        - echo Build completed on `date`
        - echo Pushing the Docker images...
        - docker push $REPOSITORY_URI:$IMAGE_TAG
        - docker push $REPOSITORY_URI:$(echo $CODEBUILD_BUILD_ID | sed 's/:/-/')
        - echo Writing image definitions file...
        - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json